on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # runs every 30 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start App Loop
        run: |
          while true
          do
            echo "Running app..."
            node index.js
            echo "Restarting in 5 seconds..."
            sleep 5
          done
